---
title: "biathlon_data_analysis"
author: "stewarta"
date: "5 February 2018"
output: html_document
---

Today we are looking at data from biathlon results. 
```{r}
library(knitr)
womenMSdf <- read.csv(file = "biathlon_women_world_mass_start_17_12_17.csv")
kable(head(womenMSdf))
```

# Rank according to number of penalties
```{r}
library(ggplot2)
ggplot(womenMSdf, aes(x=womenMSdf$Rank, y=womenMSdf$num_Penalties)) + geom_point()
```
# rank according to num of rank points obtained in championship that year
```{r}

ggplot(womenMSdf, aes(x=womenMSdf$Rank, y=womenMSdf$WC_points)) + geom_point()
```



#Number of participants per country

```{r}
library(ggplot2)
ggplot(womenMSdf, aes(x=womenMSdf$Nat)) + geom_bar()
```

#Number of penalties per country

```{r}
library(ggplot2)
library(sqldf)
dfnew <- sqldf("SELECT distinct Nat,count(Nat),count(num_Penalties) FROM womenMSdf GROUP BY Nat")
ggplot(dfnew, aes(x=dfnew$Nat)) + geom_col(aes(x=dfnew$Nat, y=(dfnew$count(num_Penalties)/dfnew$count(Nat))))
ggplot(dfnew) + geom_col(dfnew <- sqldf("SELECT distinct Nat,count(Nat),count(num_Penalties) FROM womenMSdf GROUP BY Nat")
)
```

